# Generated by Django 3.2.19 on 2023-08-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0002_auto_20230823_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
