# Generated by Django 4.2.2 on 2023-08-23 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset_app', '0006_company_created_at_company_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delegation',
            name='checkout_date',
        ),
        migrations.RemoveField(
            model_name='delegation',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='delegation',
            name='start_date',
        ),
        migrations.AddField(
            model_name='delegation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delegation',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_delegation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delegation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='delegation',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_delegation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asset',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_asset', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_comapany', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companyemployee',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employees', to=settings.AUTH_USER_MODEL),
        ),
    ]
